<a href="https://www.kaggle.com/code/sabbirhardworker/mlb-2-class-5-assignment?scriptVersionId=346924806" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [17]:
import numpy as np
import pandas as pd

In [6]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [7]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [22]:

arr_1d = np.array([1, 2, 3])
print(f"1D Array:\n{arr_1d}\n")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr_2d}\n")

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr_3d}\n")

arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], 
                   [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(f"4D Array:\n{arr_4d}")

1D Array:
[1 2 3]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [23]:

res_1d = np.arange(10)
print(f"1D Array:\n{res_1d}\n")

res_2d = np.arange(16).reshape(4, 4)
print(f"2D Array:\n{res_2d}\n")

res_3d = np.arange(27).reshape(3, 3, 3)
print(f"3D Array:\n{res_3d}\n")

res_4d = np.arange(81).reshape(3, 3, 3, 3)
print(f"4D Array:\n{res_4d}")

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

3D Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

4D Array:
[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]
   [60 61 62]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]


# create array using ones and zeros

In [24]:

ones_arr = np.ones((4, 4))
print(f"Ones Array:\n{ones_arr}\n")

zeros_arr = np.zeros((5, 5))
print(f"Zeros Array:\n{zeros_arr}")

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros Array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# using random

In [26]:

rand_arr = (np.random.random((3, 5)) * 1000)
print(f"Random Array:\n{rand_arr}")

Random Array:
[[379.58489944 508.75800723 617.79674762 152.86024364 445.34622908]
 [968.70812369 162.82418081 781.96527217 717.34164369 830.17105935]
 [476.07871431 537.24138111 169.98816979 258.78631871 915.81380325]]


# using linspace

In [28]:

lin_arr = np.linspace(10, 100, 20, dtype=int)
print(f"Linspace Array:\n{lin_arr}")

Linspace Array:
[ 10  14  19  24  28  33  38  43  47  52  57  62  66  71  76  81  85  90
  95 100]


# create 1D array of tip from tips dataframe

In [33]:

tip_1d = tips['tip'].to_numpy()
print(f"1D Array of tips:\n{tip_1d}")

1D Array of tips:
[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    

# create 2D array of tip and total_bill form tips dataframe

In [34]:

tip_bill_2d = tips[['tip', 'total_bill']].to_numpy()
print(f"2D Array of tip and total_bill:\n{tip_bill_2d}")

2D Array of tip and total_bill:
[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [35]:

print("1D ndim:", tip_1d.ndim)
print("1D shape:", tip_1d.shape)
print("1D size:", np.size(tip_1d))
print("1D itemsize (bytes):", tip_1d.itemsize)

print("\n2D ndim:", tip_bill_2d.ndim)
print("2D shape:", tip_bill_2d.shape)
print("2D size:", np.size(tip_bill_2d))
print("2D itemsize (bytes):", tip_bill_2d.itemsize)

1D ndim: 1
1D shape: (244,)
1D size: 244
1D itemsize (bytes): 8

2D ndim: 2
2D shape: (244, 2)
2D size: 488
2D itemsize (bytes): 8


# change data type and memory size of any np-array using astype()

In [36]:
print(f"Original dtype: {tip_1d.dtype} | itemsize: {tip_1d.itemsize}")

tip_1d_float32 = tip_1d.astype(np.float32)

print(f"New dtype: {tip_1d_float32.dtype} | itemsize: {tip_1d_float32.itemsize}")

Original dtype: float64 | itemsize: 8
New dtype: float32 | itemsize: 4


# create 2 same dimensional array and do scalar and vector operations

In [37]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12, 24).reshape(3, 4)

print(f"Scalar Multiplication:\n{a * 2}\n")
print(f"Scalar Power:\n{a ** 2}\n")

print(f"Vector Addition:\n{a + b}\n")
print(f"Vector Multiplication:\n{a * b}")

Scalar Multiplication:
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

Scalar Power:
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]

Vector Addition:
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Vector Multiplication:
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


# find minimun and maximum tip

In [38]:
print(f"Minimum tip: {np.min(tip_1d)}")
print(f"Maximum tip: {np.max(tip_1d)}")

Minimum tip: 1.0
Maximum tip: 10.0


# find average total_bill and average tip

In [39]:
total_bill_1d = tips['total_bill'].to_numpy()
print(f"Average total_bill: {np.mean(total_bill_1d)}")
print(f"Average tip: {np.mean(tip_1d)}")

Average total_bill: 19.78594262295082
Average tip: 2.99827868852459


# find median total_bill

In [40]:
print(f"Median total_bill: {np.median(total_bill_1d)}")

Median total_bill: 17.795


# find standard deviasion and variance of tip

In [41]:
print(f"Standard Deviation of tip: {np.std(tip_1d)}")
print(f"Variance of tip: {np.var(tip_1d)}")

Standard Deviation of tip: 1.3807999538298954
Variance of tip: 1.9066085124966412


# find log values of tip

In [42]:
tip_log = np.log(tip_1d)
print(f"Log values of tip:\n{tip_log}")

Log values of tip:
[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436

# apply round, floor and ceil operation on tip array

In [43]:
print(f"Round:\n{np.round(tip_1d, 1)}\n")
print(f"Floor:\n{np.floor(tip_1d)}\n")
print(f"Ceil:\n{np.ceil(tip_1d)}")

Round:
[ 1.   1.7  3.5  3.3  3.6  4.7  2.   3.1  2.   3.2  1.7  5.   1.6  3.
  3.   3.9  1.7  3.7  3.5  3.4  4.1  2.8  2.2  7.6  3.2  2.3  2.   2.
  4.3  3.   1.4  2.5  3.   2.4  3.3  3.6  2.   3.1  2.3  5.   2.2  2.5
  3.1  1.3  5.6  3.   5.   6.   2.   3.   2.5  2.6  5.2  1.6  4.3  3.5
  3.   1.5  1.8  6.7  3.2  2.   2.   3.8  2.6  3.2  2.5  1.   2.   2.1
  2.   3.   3.1  5.   2.2  1.2  3.1  4.   3.   2.7  3.   3.4  1.8  5.
  2.   5.2  2.   4.   5.8  3.   3.   3.5  1.   4.3  3.2  4.7  4.   1.5
  3.   1.5  2.5  3.   2.5  3.5  4.1  1.6  4.1  4.3  3.8  4.   3.   1.
  4.   2.6  4.   3.5  5.1  1.5  1.8  2.9  2.3  1.7  2.5  2.   2.5  4.2
  1.5  2.   2.   2.2  1.5  2.8  1.5  2.   3.2  1.2  2.   2.   2.   2.8
  3.5  6.7  5.   5.   2.3  1.5  1.4  1.6  1.7  2.   2.5  2.   2.7  2.
  2.   5.1  5.   3.8  2.6  2.   3.5  2.5  2.   2.   3.   3.5  2.2  4.5
  1.6  2.  10.   3.2  5.2  3.2  4.   3.1  2.   2.   4.   3.6  3.7  5.6
  3.5  6.5  3.   5.   3.5  2.   3.5  4.   1.5  4.2  2.6  2.   4.   1.4
  2.

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [45]:
x = np.arange(10)
y = np.arange(12).reshape(3, 4)
z = np.arange(27).reshape(3, 3, 3)

print(f"1D Ex1: {x[4:7]}") 
print(f"1D Ex2: {x[:5]}")
print(f"1D Ex3: {x[::2]}")
print(f"1D Ex4: {x[-3:]}")
print(f"1D Ex5: {x[1:8:2]}")

print(f"\n2D Ex1:\n{y[:1, :]}") 
print(f"2D Ex2:\n{y[1:2, 2:4]}") 
print(f"2D Ex3:\n{y[1:, 1:3]}") 
print(f"2D Ex4:\n{y[:, -1]}")
print(f"2D Ex5:\n{y[::2, ::2]}")


print(f"\n3D Ex1:\n{z[0, 1:2, :]}") 
print(f"3D Ex2:\n{z[1, 1:2, :]}") 
print(f"3D Ex3:\n{z[:2, 1:2, 1:3]}") 
print(f"3D Ex4:\n{z[1, 1:3, 1:3]}") 
print(f"3D Ex5:\n{z[:, :, 0]}")

1D Ex1: [4 5 6]
1D Ex2: [0 1 2 3 4]
1D Ex3: [0 2 4 6 8]
1D Ex4: [7 8 9]
1D Ex5: [1 3 5 7]

2D Ex1:
[[0 1 2 3]]
2D Ex2:
[[6 7]]
2D Ex3:
[[ 5  6]
 [ 9 10]]
2D Ex4:
[ 3  7 11]
2D Ex5:
[[ 0  2]
 [ 8 10]]

3D Ex1:
[[3 4 5]]
3D Ex2:
[[12 13 14]]
3D Ex3:
[[[ 4  5]]

 [[13 14]]]
3D Ex4:
[[13 14]
 [16 17]]
3D Ex5:
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


# stacking and spliting

In [47]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [48]:

print("hstack:\n", np.hstack((d, e)))

print("vstack:\n", np.vstack((d, e)))

hstack:
 [[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]
vstack:
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [49]:


print(f"hsplit (3 sections):\n{np.hsplit(d, 3)}\n")
print(f"vsplit (3 sections):\n{np.vsplit(e, 3)}")

hsplit (3 sections):
[array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]]), array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])]

vsplit (3 sections):
[array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]), array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]
